#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# set black background forcibly (maybe overlay is not needed anymore)
/usr/bin/fbsetroot -solid black

# Change your keymap:
xmodmap "/home/fafa/.Xmodmap"
[ -f /usr/bin/setxkbmap ] && /usr/bin/setxkbmap ch

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# BEGIN AUTOSTART ---------------------------------------------------------

#source /home/fafa/.bashrc
#truecrypt /data/bizz
#lan
#/sbin/ifconfig|egrep '192.1'
#if [ ${?} -ne 0 ]; then
#	dhclient eth0
#fi

# Autostart Home only
/sbin/ifconfig|egrep '192.168.85.(10|21|22)'
if [ "${?}" = "0" ]; then
	icedove &
    kate /tmp/notesx.y.z.txt &
fi

# Autostart Ganja only
/sbin/ifconfig|egrep '192.168.85.10'
if [ "${?}" = "0" ]; then
	xchat &
fi

# Autostart Netstream only
/sbin/ifconfig|egrep '192.168.1.116'
if [ "${?}" = "0" ]; then
    virtualbox&
    kate ~/stuff/notes/notes_`date +"%Y-%m-%d"`.txt&
fi

# Autostart anyway
xrdb -load ~/.Xresources
urxvt &
urxvt &
# urxvt -name urxvt-desktop-top -e htop&
urxvt -name urxvt-desktop-topleft -e top&
urxvt -name urxvt-desktop-topright -hold -e mutt&
urxvt -name urxvt-desktop-bottomleft -e sudo tail -f /var/log/syslog&
urxvt -name urxvt-desktop-bottomrightleft -hold -e cal -yh&
#urxvt -name urxvt-desktop-bottomrightright -hold -e olive&
#urxvt -name urxvt-desktop-bottomrightright -e note&
# urxvt -name URxvt-remote&
skype &
pidgin &
chromium &
xscreensaver&
gkrellm -w &

# END AUTOSTART -----------------------------------------------------------

#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox -log "/home/fafa/.fluxbox/log"
# or if you want to keep a log:
# exec fluxbox -log "/home/fafa/.fluxbox/log"
